name: 'Nookworm'
description: 'Bookmark generator'
inputs:
  config: 
    description: 'The config YAML you want to use to generate bookmarks'
    required: true
    default: 'https://raw.githubusercontent.com/thearegee/bookworm/main/demo/config/bookmarks.yaml'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
