name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  updating:
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Updating bookmarks
        committer: GitHub <noreply@github.com>
        title: 'Updating bookmarks'
        labels: automated pr
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"